### ISSUE TITLE
Better Variable Names

### ISSUE THREAD

**Issue by anuragrao04** [anuragrao04/scraper#2]
## About

The variable names in `scraper.py` is not descriptive. This is bad for readability. Please correct this and rename with descriptive variable/function names. 

## Resources

- [Official Python Style Guide](https://peps.python.org/pep-0008/#function-and-variable-names)

## Bounty 20

**Comment by g-anupam** [comment]
can i get assigned

**Comment by SNEH-17PATEL** [comment]
CAN I GET ASSIGNED??????

**Comment by N0Xl0US** [comment]
can i get assigned

**Comment by rojasbinny-yb** [comment]
Can I get assigned?

**Comment by User-LazySloth** [comment]
Please assign this issue to me!

**Comment by RitwikAg120** [comment]
Please assign this issue

**Comment by Archit-Rode** [comment]
Can i get assigned please

**Comment by Manvith-M-Nayak** [comment]
can i get assigned?

**Comment by anuragrao04** [comment]
@g-anupam Please go ahead. Everyone else, I'm sorry but it's a first come first serve basis. You'll be able to get this issue only if the first person fails to complete.

**Comment by AmeyaKhanzode** [comment]
can i get assigned?

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by euphoricair7** [comment]
can I get this issue assigned?

**Comment by sid-nc** [comment]
can i get assigned

**Comment by anuragrao04** [comment]
@g-anupam is working on this and has made a PR. I cannot assign it to other people as long as he is working on it

**Comment by tanishhegde** [comment]
Can I get assigned to this

**Comment by siri-n-shetty** [comment]
Could I get assigned?

**Comment by siri-n-shetty** [comment]
Could I get assigned, please???

**Comment by anuragrao04** [comment]
This issue has been resolved by @g-anupam
